export const simpleYaml = {
  publiccodeYmlVersion: "0.2",
  categories: ["it-development"],
  description: {
    it: {
      features: [
        "Generazione di publiccode.yml",
        "Modifica di publiccode.yml",
        "Validazione di publiccode.yml",
        "Importazione di publiccode.yml tramite URL",
        "Possibilità di gestire diverse lingue",
      ],
      genericName: "Generatore di publiccode.yml",
      longDescription:
        "publiccode editor è un'applicazione web per generare file\n[`publiccode.yml`](https://github.com/italia/publiccode.yml) validi.\nCompilando il form, genera automaticamente un file YAML compatible con\nl'ultima versione dello standard publiccode. Questo file può essere copiato\no scaricato localmente per essere poi inserito nel repository di destinazione.\n\nPuò inoltre essere usato come validatore. È possible incollare o importare\nun file `publiccode.yml` esistente all'interno dell'editor. L'editor validerà\nil documento importato e aiuterà a correggere eventuali errori.\n",
      shortDescription:
        "Un editor web per generare e validare file publiccode.yml.",
    },
  },
  developmentStatus: "stable",
  it: {
    countryExtensionVersion: "0.2",
    piattaforme: {
      anpr: false,
      cie: false,
      pagopa: false,
      spid: false,
    },
    riuso: {
      codiceIPA: "pcm",
    },
  },
  legal: {
    license: "AGPL-3.0-or-later",
    authorsFile: "AUTHORS.md",
  },
  localisation: {
    availableLanguages: ["en"],
    localisationReady: false,
  },
  maintenance: {
    contacts: [
      {
        name: "Leonardo Favario",
      },
      {
        name: "Alessandro Sebastiani",
      },
      {
        name: "Fabio Bonelli",
      },
    ],
    type: "community",
  },
  name: "publiccode editor",
  platforms: ["web"],
  releaseDate: "2020-08-20",
  softwareType: "standalone/web",
  url: "https://github.com/italia/publiccode-editor",
};

export const simpleFormYaml = {
  publiccodeYmlVersion: "0.2",
  categories: ["it-development"],
  description: {
    it: {
      features: [
        {value: "Generazione di publiccode.yml"},
        {value: "Modifica di publiccode.yml"},
        {value: "Validazione di publiccode.yml"},
        {value: "Importazione di publiccode.yml tramite URL"},
        {value: "Possibilità di gestire diverse lingue"},
      ],
      genericName: "Generatore di publiccode.yml",
      longDescription:
        "publiccode editor è un'applicazione web per generare file\n[`publiccode.yml`](https://github.com/italia/publiccode.yml) validi.\nCompilando il form, genera automaticamente un file YAML compatible con\nl'ultima versione dello standard publiccode. Questo file può essere copiato\no scaricato localmente per essere poi inserito nel repository di destinazione.\n\nPuò inoltre essere usato come validatore. È possible incollare o importare\nun file `publiccode.yml` esistente all'interno dell'editor. L'editor validerà\nil documento importato e aiuterà a correggere eventuali errori.\n",
      shortDescription:
        "Un editor web per generare e validare file publiccode.yml.",
    },
  },
  developmentStatus: "stable",
  it: {
    countryExtensionVersion: "0.2",
    piattaforme: {
      anpr: false,
      cie: false,
      pagopa: false,
      spid: false,
    },
    riuso: {
      codiceIPA: "pcm",
    },
  },
  legal: {
    license: "AGPL-3.0-or-later",
    authorsFile: "AUTHORS.md",
  },
  localisation: {
    availableLanguages: ["en"],
    localisationReady: false,
  },
  maintenance: {
    contacts: [
      {
        name: "Leonardo Favario",
      },
      {
        name: "Alessandro Sebastiani",
      },
      {
        name: "Fabio Bonelli",
      },
    ],
    type: "community",
  },
  name: "publiccode editor",
  platforms: ["web"],
  releaseDate: "2020-08-20",
  softwareType: "standalone/web",
  url: "https://github.com/italia/publiccode-editor",
};

export const yamlFlattened = {
  publiccodeYmlVersion: "0.2",
  categories: ["it-development"],
  "description.it.features": [
    "Generazione di publiccode.yml",
    "Modifica di publiccode.yml",
    "Validazione di publiccode.yml",
    "Importazione di publiccode.yml tramite URL",
    "Possibilità di gestire diverse lingue",
  ],
  "description.it.genericName": "Generatore di publiccode.yml",
  "description.it.longDescription":
    "publiccode editor è un'applicazione web per generare file\n" +
    "[`publiccode.yml`](https://github.com/italia/publiccode.yml) validi.\n" +
    "Compilando il form, genera automaticamente un file YAML compatible con\n" +
    "l'ultima versione dello standard publiccode. Questo file può essere copiato\n" +
    "o scaricato localmente per essere poi inserito nel repository di destinazione.\n" +
    "\n" +
    "Può inoltre essere usato come validatore. È possible incollare o importare\n" +
    "un file `publiccode.yml` esistente all'interno dell'editor. L'editor validerà\n" +
    "il documento importato e aiuterà a correggere eventuali errori.\n",
  "description.it.shortDescription":
    "Un editor web per generare e validare file publiccode.yml.",
  developmentStatus: "stable",
  "it.countryExtensionVersion": "0.2",
  "it.piattaforme.anpr": false,
  "it.piattaforme.cie": false,
  "it.piattaforme.pagopa": false,
  "it.piattaforme.spid": false,
  "it.riuso.codiceIPA": "pcm",
  "legal.license": "AGPL-3.0-or-later",
  "legal.authorsFile": "AUTHORS.md",
  "localisation.availableLanguages": ["en"],
  "localisation.localisationReady": false,
  "maintenance.contacts": [
    { name: "Leonardo Favario" },
    { name: "Alessandro Sebastiani" },
    { name: "Fabio Bonelli" },
  ],
  "maintenance.type": "community",
  name: "publiccode editor",
  platforms: ["web"],
  releaseDate: "2020-08-20",
  softwareType: "standalone/web",
  url: "https://github.com/italia/publiccode-editor",
};

export const yamlFlattenedSimpleArray = {
  publiccodeYmlVersion: "0.2",
  categories: ["it-development"],
  "description.it.features": [
    { value: "Generazione di publiccode.yml" },
    { value: "Modifica di publiccode.yml" },
    { value: "Validazione di publiccode.yml" },
    { value: "Importazione di publiccode.yml tramite URL" },
    { value: "Possibilità di gestire diverse lingue" },
  ],
  "description.it.genericName": "Generatore di publiccode.yml",
  "description.it.longDescription":
    "publiccode editor è un'applicazione web per generare file\n[`publiccode.yml`](https://github.com/italia/publiccode.yml) validi.\nCompilando il form, genera automaticamente un file YAML compatible con\nl'ultima versione dello standard publiccode. Questo file può essere copiato\no scaricato localmente per essere poi inserito nel repository di destinazione.\n\nPuò inoltre essere usato come validatore. È possible incollare o importare\nun file `publiccode.yml` esistente all'interno dell'editor. L'editor validerà\nil documento importato e aiuterà a correggere eventuali errori.\n",
  "description.it.shortDescription":
    "Un editor web per generare e validare file publiccode.yml.",
  developmentStatus: "stable",
  "it.countryExtensionVersion": "0.2",
  "it.piattaforme.anpr": false,
  "it.piattaforme.cie": false,
  "it.piattaforme.pagopa": false,
  "it.piattaforme.spid": false,
  "it.riuso.codiceIPA": "pcm",
  "legal.license": "AGPL-3.0-or-later",
  "legal.authorsFile": "AUTHORS.md",
  "localisation.availableLanguages": ["en"],
  "localisation.localisationReady": false,
  "maintenance.contacts": [
    { name: "Leonardo Favario" },
    { name: "Alessandro Sebastiani" },
    { name: "Fabio Bonelli" },
  ],
  "maintenance.type": "community",
  name: "publiccode editor",
  platforms: ["web"],
  releaseDate: "2020-08-20",
  softwareType: "standalone/web",
  url: "https://github.com/italia/publiccode-editor",
};

export const allFields = [
  {
    title: "description.it.localisedName",
    type: "string",
    section: 0,
    group: "description",
    language: true,
    rawTitle: "description.localisedName",
    lang: "it",
  },
  {
    title: "description.it.genericName",
    type: "string",
    section: 0,
    maxLength: 35,
    required: true,
    group: "description",
    language: true,
    rawTitle: "description.genericName",
    lang: "it",
  },
  {
    title: "description.it.shortDescription",
    type: "string",
    section: 4,
    maxLength: 150,
    group: "description",
    language: true,
    required: true,
    rawTitle: "description.shortDescription",
    lang: "it",
  },
  {
    title: "description.it.longDescription",
    type: "string",
    section: 4,
    group: "description",
    language: true,
    widget: "editor",
    required: true,
    minLength: 500,
    maxLength: 10000,
    cn: "block__item--full",
    rawTitle: "description.longDescription",
    lang: "it",
  },
  {
    title: "description.it.documentation",
    type: "string",
    section: 1,
    group: "description",
    widget: "url",
    language: true,
    rawTitle: "description.documentation",
    lang: "it",
  },
  {
    title: "description.it.apiDocumentation",
    section: 1,
    group: "description",
    type: "string",
    widget: "url",
    language: true,
    rawTitle: "description.apiDocumentation",
    lang: "it",
  },
  {
    title: "description.it.features",
    type: "array",
    items: {
      title: "feature",
      type: "object",
      properties: {
        value: {
          type: "string",
          title: "value",
          isSummary: true,
        },
      },
    },
    section: 4,
    required: true,
    language: true,
    simpleStringArray: true,
    group: "description",
    rawTitle: "description.features",
    lang: "it",
  },
  {
    title: "publiccodeYmlVersion",
    type: "hidden",
    section: 0,
    required: true,
  },
  {
    title: "name",
    type: "string",
    section: 0,
    required: true,
  },
  {
    title: "releaseDate",
    type: "string",
    section: 2,
    required: true,
    widget: "date",
  },
  {
    title: "url",
    type: "string",
    widget: "url",
    section: 1,
    required: true,
  },
  {
    title: "applicationSuite",
    type: "string",
    section: 0,
  },
  {
    type: "string",
    title: "landingURL",
    section: 1,
    widget: "url",
  },
  {
    title: "description.screenshots",
    type: "array",
    items: {
      type: "string",
      title: "screenshot",
    },
    section: 5,
    group: "description",
  },
  {
    title: "description.videos",
    type: "array",
    items: {
      type: "string",
      title: "video",
    },
    section: 5,
    group: "description",
  },
  {
    title: "description.awards",
    type: "array",
    items: {
      type: "string",
      title: "award",
    },
    section: 3,
    group: "description",
  },
  {
    title: "isBasedOn",
    type: "array",
    items: {
      type: "string",
      title: "isBasedOn",
    },
    section: 2,
    widget: "url",
  },
  {
    type: "string",
    title: "softwareVersion",
    section: 2,
  },
  {
    type: "string",
    title: "logo",
    section: 5,
    fileExt: ["svg", "svgz", "png"],
  },
  {
    type: "string",
    title: "monochromeLogo",
    section: 5,
    fileExt: ["svg", "svgz", "png"],
  },
  {
    title: "developmentStatus",
    type: "string",
    enum: ["concept", "development", "beta", "stable", "obsolete"],
    section: 2,
    required: true,
    widget: "choice-expanded",
  },
  {
    title: "softwareType",
    type: "string",
    enum: [
      "standalone/backend",
      "standalone/desktop",
      "standalone/iot",
      "standalone/mobile",
      "standalone/web",
      "standalone/other",
      "addon",
      "library",
      "configurationFiles",
    ],
    section: 2,
    required: true,
    widget: "choice-expanded",
  },
  {
    title: "roadmap",
    type: "string",
    section: 1,
    widget: "url",
  },
  {
    type: "array",
    title: "platforms",
    examples: ["android", "ios"],
    items: {
      type: "string",
      enum: ["web", "windows", "mac", "linux", "ios", "android"],
    },
    required: true,
    section: 2,
    widget: "tags",
  },
  {
    type: "array",
    title: "legal.license",
    section: 3,
    items: {
      type: "string",
      enum: [
        {
          text: "BSD Zero Clause License",
          value: "0BSD",
        },
        {
          text: "Attribution Assurance License",
          value: "AAL",
        },
        {
          text: "Academic Free License v1.1",
          value: "AFL-1.1",
        },
        {
          text: "Academic Free License v1.2",
          value: "AFL-1.2",
        },
        {
          text: "Academic Free License v2.0",
          value: "AFL-2.0",
        },
        {
          text: "Academic Free License v2.1",
          value: "AFL-2.1",
        },
        {
          text: "Academic Free License v3.0",
          value: "AFL-3.0",
        },
        {
          text: "GNU Affero General Public License v3.0 only",
          value: "AGPL-3.0-only",
        },
        {
          text: "GNU Affero General Public License v3.0 or later",
          value: "AGPL-3.0-or-later",
        },
        {
          text: "Adaptive Public License 1.0",
          value: "APL-1.0",
        },
        {
          text: "Apple Public Source License 1.0",
          value: "APSL-1.0",
        },
        {
          text: "Apple Public Source License 1.1",
          value: "APSL-1.1",
        },
        {
          text: "Apple Public Source License 1.2",
          value: "APSL-1.2",
        },
        {
          text: "Apple Public Source License 2.0",
          value: "APSL-2.0",
        },
        {
          text: "Apache License 1.1",
          value: "Apache-1.1",
        },
        {
          text: "Apache License 2.0",
          value: "Apache-2.0",
        },
        {
          text: "Artistic License 1.0",
          value: "Artistic-1.0",
        },
        {
          text: "Artistic License 1.0 (Perl)",
          value: "Artistic-1.0-Perl",
        },
        {
          text: "Artistic License 1.0 w/clause 8",
          value: "Artistic-1.0-cl8",
        },
        {
          text: "Artistic License 2.0",
          value: "Artistic-2.0",
        },
        {
          text: 'BSD 2-Clause "Simplified" License',
          value: "BSD-2-Clause",
        },
        {
          text: "BSD-2-Clause Plus Patent License",
          value: "BSD-2-Clause-Patent",
        },
        {
          text: 'BSD 3-Clause "New" or "Revised" License',
          value: "BSD-3-Clause",
        },
        {
          text: "Boost Software License 1.0",
          value: "BSL-1.0",
        },
        {
          text: "Computer Associates Trusted Open Source License 1.1",
          value: "CATOSL-1.1",
        },
        {
          text: "Common Development and Distribution License 1.0",
          value: "CDDL-1.0",
        },
        {
          text: "CeCILL Free Software License Agreement v2.1",
          value: "CECILL-2.1",
        },
        {
          text: "CNRI Python License",
          value: "CNRI-Python",
        },
        {
          text: "Common Public Attribution License 1.0",
          value: "CPAL-1.0",
        },
        {
          text: "Common Public License 1.0",
          value: "CPL-1.0",
        },
        {
          text: "CUA Office Public License v1.0",
          value: "CUA-OPL-1.0",
        },
        {
          text: "Educational Community License v1.0",
          value: "ECL-1.0",
        },
        {
          text: "Educational Community License v2.0",
          value: "ECL-2.0",
        },
        {
          text: "Eiffel Forum License v1.0",
          value: "EFL-1.0",
        },
        {
          text: "Eiffel Forum License v2.0",
          value: "EFL-2.0",
        },
        {
          text: "Eclipse Public License 1.0",
          value: "EPL-1.0",
        },
        {
          text: "Eclipse Public License 2.0",
          value: "EPL-2.0",
        },
        {
          text: "EU DataGrid Software License",
          value: "EUDatagrid",
        },
        {
          text: "European Union Public License 1.1",
          value: "EUPL-1.1",
        },
        {
          text: "European Union Public License 1.2",
          value: "EUPL-1.2",
        },
        {
          text: "Entessa Public License v1.0",
          value: "Entessa",
        },
        {
          text: "Fair License",
          value: "Fair",
        },
        {
          text: "Frameworx Open License 1.0",
          value: "Frameworx-1.0",
        },
        {
          text: "GNU General Public License v2.0 only",
          value: "GPL-2.0-only",
        },
        {
          text: "GNU General Public License v2.0 or later",
          value: "GPL-2.0-or-later",
        },
        {
          text: "GNU General Public License v3.0 only",
          value: "GPL-3.0-only",
        },
        {
          text: "GNU General Public License v3.0 or later",
          value: "GPL-3.0-or-later",
        },
        {
          text: "Historical Permission Notice and Disclaimer",
          value: "HPND",
        },
        {
          text: "IPA Font License",
          value: "IPA",
        },
        {
          text: "IBM Public License v1.0",
          value: "IPL-1.0",
        },
        {
          text: "ISC License",
          value: "ISC",
        },
        {
          text: "Intel Open Source License",
          value: "Intel",
        },
        {
          text: "GNU Library General Public License v2 only",
          value: "LGPL-2.0-only",
        },
        {
          text: "GNU Library General Public License v2 or later",
          value: "LGPL-2.0-or-later",
        },
        {
          text: "GNU Lesser General Public License v2.1 only",
          value: "LGPL-2.1-only",
        },
        {
          text: "GNU Lesser General Public License v2.1 or later",
          value: "LGPL-2.1-or-later",
        },
        {
          text: "GNU Lesser General Public License v3.0 only",
          value: "LGPL-3.0-only",
        },
        {
          text: "GNU Lesser General Public License v3.0 or later",
          value: "LGPL-3.0-or-later",
        },
        {
          text: "Lucent Public License Version 1.0",
          value: "LPL-1.0",
        },
        {
          text: "Lucent Public License v1.02",
          value: "LPL-1.02",
        },
        {
          text: "LaTeX Project Public License v1.3c",
          value: "LPPL-1.3c",
        },
        {
          text: "Licence Libre du Québec – Permissive version 1.1",
          value: "LiLiQ-P-1.1",
        },
        {
          text: "Licence Libre du Québec – Réciprocité version 1.1",
          value: "LiLiQ-R-1.1",
        },
        {
          text: "Licence Libre du Québec – Réciprocité forte version 1.1",
          value: "LiLiQ-Rplus-1.1",
        },
        {
          text: "MIT License",
          value: "MIT",
        },
        {
          text: "MIT No Attribution",
          value: "MIT-0",
        },
        {
          text: "Mozilla Public License 1.0",
          value: "MPL-1.0",
        },
        {
          text: "Mozilla Public License 1.1",
          value: "MPL-1.1",
        },
        {
          text: "Mozilla Public License 2.0",
          value: "MPL-2.0",
        },
        {
          text: "Mozilla Public License 2.0 (no copyleft exception)",
          value: "MPL-2.0-no-copyleft-exception",
        },
        {
          text: "Microsoft Public License",
          value: "MS-PL",
        },
        {
          text: "Microsoft Reciprocal License",
          value: "MS-RL",
        },
        {
          text: "The MirOS Licence",
          value: "MirOS",
        },
        {
          text: "Motosoto License",
          value: "Motosoto",
        },
        {
          text: "Multics License",
          value: "Multics",
        },
        {
          text: "NASA Open Source Agreement 1.3",
          value: "NASA-1.3",
        },
        {
          text: "University of Illinois/NCSA Open Source License",
          value: "NCSA",
        },
        {
          text: "Nethack General Public License",
          value: "NGPL",
        },
        {
          text: "Non-Profit Open Software License 3.0",
          value: "NPOSL-3.0",
        },
        {
          text: "NTP License",
          value: "NTP",
        },
        {
          text: "Naumen Public License",
          value: "Naumen",
        },
        {
          text: "Nokia Open Source License",
          value: "Nokia",
        },
        {
          text: "OCLC Research Public License 2.0",
          value: "OCLC-2.0",
        },
        {
          text: "SIL Open Font License 1.1",
          value: "OFL-1.1",
        },
        {
          text: "Open Group Test Suite License",
          value: "OGTSL",
        },
        {
          text: "OSET Public License version 2.1",
          value: "OSET-PL-2.1",
        },
        {
          text: "Open Software License 1.0",
          value: "OSL-1.0",
        },
        {
          text: "Open Software License 2.0",
          value: "OSL-2.0",
        },
        {
          text: "Open Software License 2.1",
          value: "OSL-2.1",
        },
        {
          text: "Open Software License 3.0",
          value: "OSL-3.0",
        },
        {
          text: "PHP License v3.0",
          value: "PHP-3.0",
        },
        {
          text: "PostgreSQL License",
          value: "PostgreSQL",
        },
        {
          text: "Python License 2.0",
          value: "Python-2.0",
        },
        {
          text: "Q Public License 1.0",
          value: "QPL-1.0",
        },
        {
          text: "Reciprocal Public License 1.1",
          value: "RPL-1.1",
        },
        {
          text: "Reciprocal Public License 1.5",
          value: "RPL-1.5",
        },
        {
          text: "RealNetworks Public Source License v1.0",
          value: "RPSL-1.0",
        },
        {
          text: "Ricoh Source Code Public License",
          value: "RSCPL",
        },
        {
          text: "Sun Industry Standards Source License v1.1",
          value: "SISSL",
        },
        {
          text: "Sun Public License v1.0",
          value: "SPL-1.0",
        },
        {
          text: "Simple Public License 2.0",
          value: "SimPL-2.0",
        },
        {
          text: "Sleepycat License",
          value: "Sleepycat",
        },
        {
          text: "Universal Permissive License v1.0",
          value: "UPL-1.0",
        },
        {
          text: "Vovida Software License v1.0",
          value: "VSL-1.0",
        },
        {
          text: "W3C Software Notice and License (2002-12-31)",
          value: "W3C",
        },
        {
          text: "Sybase Open Watcom Public License 1.0",
          value: "Watcom-1.0",
        },
        {
          text: "X.Net License",
          value: "Xnet",
        },
        {
          text: "Zope Public License 2.0",
          value: "ZPL-2.0",
        },
        {
          text: "zlib License",
          value: "Zlib",
        },
      ],
    },
    group: "legal",
    required: true,
    widget: "combobox",
  },
  {
    type: "string",
    title: "legal.mainCopyrightOwner",
    section: 3,
    group: "legal",
  },
  {
    type: "string",
    title: "legal.repoOwner",
    section: 3,
    group: "legal",
    required: false,
  },
  {
    title: "legal.authorsFile",
    type: "string",
    section: 3,
    group: "legal",
  },
  {
    title: "categories",
    type: "array",
    items: {
      type: "string",
      title: "category",
      enum: [
        "accounting",
        "agile-project-management",
        "applicant-tracking",
        "application-development",
        "appointment-scheduling",
        "backup",
        "billing-and-invoicing",
        "blog",
        "budgeting",
        "business-intelligence",
        "business-process-management",
        "cad",
        "call-center-management",
        "cloud-management",
        "collaboration",
        "communications",
        "compliance-management",
        "contact-management",
        "content-management",
        "crm",
        "customer-service-and-support",
        "data-analytics",
        "data-collection",
        "data-visualization",
        "digital-asset-management",
        "digital-citizenship",
        "document-management",
        "donor-management",
        "e-commerce",
        "e-signature",
        "email-management",
        "email-marketing",
        "employee-management",
        "enterprise-project-management",
        "enterprise-social-networking",
        "erp",
        "event-management",
        "facility-management",
        "feedback-and-reviews-management",
        "financial-reporting",
        "fleet-management",
        "fundraising",
        "gamification",
        "geographic-information-systems",
        "grant-management",
        "graphic-design",
        "help-desk",
        "hr",
        "ide",
        "identity-management",
        "instant-messaging",
        "inventory-management",
        "it-asset-management",
        "it-development",
        "it-management",
        "it-security",
        "it-service-management",
        "knowledge-management",
        "learning-management-system",
        "marketing",
        "mind-mapping",
        "mobile-marketing",
        "mobile-payment",
        "network-management",
        "office",
        "online-booking",
        "online-community",
        "payment-gateway",
        "payroll",
        "predictive-analysis",
        "procurement",
        "productivity-suite",
        "project-collaboration",
        "project-management",
        "property-management",
        "real-estate-management",
        "remote-support",
        "resource-management",
        "sales-management",
        "seo",
        "service-desk",
        "social-media-management",
        "survey",
        "talent-management",
        "task-management",
        "taxes-management",
        "test-management",
        "time-management",
        "time-tracking",
        "translation",
        "video-conferencing",
        "video-editing",
        "visitor-management",
        "voip",
        "warehouse-management",
        "web-collaboration",
        "web-conferencing",
        "website-builder",
        "workflow-management",
      ],
    },
    section: 6,
    required: true,
    widget: "tags",
  },
  {
    title: "intendedAudience.scope",
    type: "array",
    items: {
      type: "string",
      title: "scope",
      enum: [
        "agriculture",
        "culture",
        "defence",
        "education",
        "emergency-services",
        "employment",
        "energy",
        "environment",
        "finance-and-economic-development",
        "foreign-affairs",
        "government",
        "healthcare",
        "infrastructures",
        "justice",
        "local-authorities",
        "manufacturing",
        "research",
        "science-and-technology",
        "security",
        "society",
        "sport",
        "tourism",
        "transportation",
        "welfare",
      ],
    },
    section: 6,
    group: "intendedAudience",
    widget: "tags",
  },
  {
    title: "intendedAudience.countries",
    type: "array",
    items: {
      title: "item",
      type: "string",
      enum: [
        "ad",
        "ae",
        "af",
        "ag",
        "ai",
        "al",
        "am",
        "ao",
        "aq",
        "ar",
        "as",
        "at",
        "au",
        "aw",
        "ax",
        "az",
        "ba",
        "bb",
        "bd",
        "be",
        "bf",
        "bg",
        "bh",
        "bi",
        "bj",
        "bl",
        "bm",
        "bn",
        "bo",
        "bq",
        "br",
        "bs",
        "bt",
        "bv",
        "bw",
        "by",
        "bz",
        "ca",
        "cc",
        "cd",
        "cf",
        "cg",
        "ch",
        "ci",
        "ck",
        "cl",
        "cm",
        "cn",
        "co",
        "cr",
        "cu",
        "cv",
        "cw",
        "cx",
        "cy",
        "cz",
        "de",
        "dj",
        "dk",
        "dm",
        "do",
        "dz",
        "ec",
        "ee",
        "eg",
        "eh",
        "er",
        "es",
        "et",
        "fi",
        "fj",
        "fk",
        "fm",
        "fo",
        "fr",
        "ga",
        "gb",
        "gd",
        "ge",
        "gf",
        "gg",
        "gh",
        "gi",
        "gl",
        "gm",
        "gn",
        "gp",
        "gq",
        "gr",
        "gs",
        "gt",
        "gu",
        "gw",
        "gy",
        "hk",
        "hm",
        "hn",
        "hr",
        "ht",
        "hu",
        "id",
        "ie",
        "il",
        "im",
        "in",
        "io",
        "iq",
        "ir",
        "is",
        "it",
        "je",
        "jm",
        "jo",
        "jp",
        "ke",
        "kg",
        "kh",
        "ki",
        "km",
        "kn",
        "kp",
        "kr",
        "kw",
        "ky",
        "kz",
        "la",
        "lb",
        "lc",
        "li",
        "lk",
        "lr",
        "ls",
        "lt",
        "lu",
        "lv",
        "ly",
        "ma",
        "mc",
        "md",
        "me",
        "mf",
        "mg",
        "mh",
        "mk",
        "ml",
        "mm",
        "mn",
        "mo",
        "mp",
        "mq",
        "mr",
        "ms",
        "mt",
        "mu",
        "mv",
        "mw",
        "mx",
        "my",
        "mz",
        "na",
        "nc",
        "ne",
        "nf",
        "ng",
        "ni",
        "nl",
        "no",
        "np",
        "nr",
        "nu",
        "nz",
        "om",
        "pa",
        "pe",
        "pf",
        "pg",
        "ph",
        "pk",
        "pl",
        "pm",
        "pn",
        "pr",
        "ps",
        "pt",
        "pw",
        "py",
        "qa",
        "re",
        "ro",
        "rs",
        "ru",
        "rw",
        "sa",
        "sb",
        "sc",
        "sd",
        "se",
        "sg",
        "sh",
        "si",
        "sj",
        "sk",
        "sl",
        "sm",
        "sn",
        "so",
        "sr",
        "ss",
        "st",
        "sv",
        "sx",
        "sy",
        "sz",
        "tc",
        "td",
        "tf",
        "tg",
        "th",
        "tj",
        "tk",
        "tl",
        "tm",
        "tn",
        "to",
        "tr",
        "tt",
        "tv",
        "tw",
        "tz",
        "ua",
        "ug",
        "um",
        "us",
        "uy",
        "uz",
        "va",
        "vc",
        "ve",
        "vg",
        "vi",
        "vn",
        "vu",
        "wf",
        "ws",
        "ye",
        "yt",
        "za",
        "zm",
        "zw",
      ],
    },
    section: 6,
    group: "intendedAudience",
    widget: "tags",
  },
  {
    title: "intendedAudience.unsupportedCountries",
    type: "array",
    items: {
      title: "item",
      type: "string",
      enum: [
        "ad",
        "ae",
        "af",
        "ag",
        "ai",
        "al",
        "am",
        "ao",
        "aq",
        "ar",
        "as",
        "at",
        "au",
        "aw",
        "ax",
        "az",
        "ba",
        "bb",
        "bd",
        "be",
        "bf",
        "bg",
        "bh",
        "bi",
        "bj",
        "bl",
        "bm",
        "bn",
        "bo",
        "bq",
        "br",
        "bs",
        "bt",
        "bv",
        "bw",
        "by",
        "bz",
        "ca",
        "cc",
        "cd",
        "cf",
        "cg",
        "ch",
        "ci",
        "ck",
        "cl",
        "cm",
        "cn",
        "co",
        "cr",
        "cu",
        "cv",
        "cw",
        "cx",
        "cy",
        "cz",
        "de",
        "dj",
        "dk",
        "dm",
        "do",
        "dz",
        "ec",
        "ee",
        "eg",
        "eh",
        "er",
        "es",
        "et",
        "fi",
        "fj",
        "fk",
        "fm",
        "fo",
        "fr",
        "ga",
        "gb",
        "gd",
        "ge",
        "gf",
        "gg",
        "gh",
        "gi",
        "gl",
        "gm",
        "gn",
        "gp",
        "gq",
        "gr",
        "gs",
        "gt",
        "gu",
        "gw",
        "gy",
        "hk",
        "hm",
        "hn",
        "hr",
        "ht",
        "hu",
        "id",
        "ie",
        "il",
        "im",
        "in",
        "io",
        "iq",
        "ir",
        "is",
        "it",
        "je",
        "jm",
        "jo",
        "jp",
        "ke",
        "kg",
        "kh",
        "ki",
        "km",
        "kn",
        "kp",
        "kr",
        "kw",
        "ky",
        "kz",
        "la",
        "lb",
        "lc",
        "li",
        "lk",
        "lr",
        "ls",
        "lt",
        "lu",
        "lv",
        "ly",
        "ma",
        "mc",
        "md",
        "me",
        "mf",
        "mg",
        "mh",
        "mk",
        "ml",
        "mm",
        "mn",
        "mo",
        "mp",
        "mq",
        "mr",
        "ms",
        "mt",
        "mu",
        "mv",
        "mw",
        "mx",
        "my",
        "mz",
        "na",
        "nc",
        "ne",
        "nf",
        "ng",
        "ni",
        "nl",
        "no",
        "np",
        "nr",
        "nu",
        "nz",
        "om",
        "pa",
        "pe",
        "pf",
        "pg",
        "ph",
        "pk",
        "pl",
        "pm",
        "pn",
        "pr",
        "ps",
        "pt",
        "pw",
        "py",
        "qa",
        "re",
        "ro",
        "rs",
        "ru",
        "rw",
        "sa",
        "sb",
        "sc",
        "sd",
        "se",
        "sg",
        "sh",
        "si",
        "sj",
        "sk",
        "sl",
        "sm",
        "sn",
        "so",
        "sr",
        "ss",
        "st",
        "sv",
        "sx",
        "sy",
        "sz",
        "tc",
        "td",
        "tf",
        "tg",
        "th",
        "tj",
        "tk",
        "tl",
        "tm",
        "tn",
        "to",
        "tr",
        "tt",
        "tv",
        "tw",
        "tz",
        "ua",
        "ug",
        "um",
        "us",
        "uy",
        "uz",
        "va",
        "vc",
        "ve",
        "vg",
        "vi",
        "vn",
        "vu",
        "wf",
        "ws",
        "ye",
        "yt",
        "za",
        "zm",
        "zw",
      ],
    },
    section: 6,
    group: "intendedAudience",
    widget: "tags",
  },
  {
    title: "usedBy",
    type: "array",
    items: {
      type: "string",
    },
    section: 3,
  },
  {
    title: "inputTypes",
    type: "array",
    items: {
      type: "string",
    },
    section: 2,
  },
  {
    title: "outputTypes",
    type: "array",
    items: {
      type: "string",
    },
    section: 2,
  },
  {
    title: "localisation.localisationReady",
    type: "boolean",
    section: 6,
    required: true,
    group: "localisation",
  },
  {
    title: "localisation.availableLanguages",
    type: "array",
    items: {
      title: "item",
      type: "string",
      enum: [
        "aa",
        "ab",
        "ae",
        "af",
        "ak",
        "am",
        "an",
        "ar",
        "as",
        "av",
        "ay",
        "az",
        "ba",
        "be",
        "bg",
        "bh",
        "bi",
        "bm",
        "bn",
        "bo",
        "br",
        "bs",
        "ca",
        "ce",
        "ch",
        "co",
        "cr",
        "cs",
        "cu",
        "cv",
        "cy",
        "da",
        "de",
        "dv",
        "dz",
        "ee",
        "el",
        "en",
        "eo",
        "es",
        "et",
        "eu",
        "fa",
        "ff",
        "fi",
        "fj",
        "fo",
        "fr",
        "fy",
        "ga",
        "gd",
        "gl",
        "gn",
        "gu",
        "gv",
        "ha",
        "he",
        "hi",
        "ho",
        "hr",
        "ht",
        "hu",
        "hy",
        "hz",
        "ia",
        "id",
        "ie",
        "ig",
        "ii",
        "ik",
        "io",
        "is",
        "it",
        "iu",
        "ja",
        "jv",
        "ka",
        "kg",
        "ki",
        "kj",
        "kk",
        "kl",
        "km",
        "kn",
        "ko",
        "kr",
        "ks",
        "ku",
        "kv",
        "kw",
        "ky",
        "la",
        "lb",
        "lg",
        "li",
        "ln",
        "lo",
        "lt",
        "lu",
        "lv",
        "mg",
        "mh",
        "mi",
        "mk",
        "ml",
        "mn",
        "mr",
        "ms",
        "mt",
        "my",
        "na",
        "nb",
        "nd",
        "ne",
        "ng",
        "nl",
        "nn",
        "no",
        "nr",
        "nv",
        "ny",
        "oc",
        "oj",
        "om",
        "or",
        "os",
        "pa",
        "pi",
        "pl",
        "ps",
        "pt",
        "qu",
        "rm",
        "rn",
        "ro",
        "ru",
        "rw",
        "sa",
        "sc",
        "sd",
        "se",
        "sg",
        "si",
        "sk",
        "sl",
        "sm",
        "sn",
        "so",
        "sq",
        "sr",
        "ss",
        "st",
        "su",
        "sv",
        "sw",
        "ta",
        "te",
        "tg",
        "th",
        "ti",
        "tk",
        "tl",
        "tn",
        "to",
        "tr",
        "ts",
        "tt",
        "tw",
        "ty",
        "ug",
        "uk",
        "ur",
        "uz",
        "ve",
        "vi",
        "vo",
        "wa",
        "wo",
        "xh",
        "yi",
        "yo",
        "za",
        "zh",
        "zu",
      ],
    },
    widget: "tags",
    section: 4,
    required: true,
    group: "localisation",
  },
  {
    title: "maintenance.type",
    type: "array",
    items: {
      type: "string",
    },
    uniqueItems: true,
    required: true,
    requireChildrenIf: [
      {
        title: "maintenance_contacts",
        values: ["internal", "community"],
      },
      {
        title: "maintenance_contractors",
        values: ["contract"],
      },
    ],
    enum: ["internal", "contract", "community", "none"],
    widget: "choice-expanded",
    section: 7,
    group: "maintenance",
  },
  {
    title: "maintenance.contacts",
    type: "array",
    items: {
      title: "contact",
      type: "object",
      properties: {
        name: {
          type: "string",
          title: "name",
          isSummary: true,
        },
        email: {
          type: "string",
          title: "Email",
          widget: "email",
          isSummary: true,
        },
        phone: {
          type: "string",
          widget: "phone",
          title: "phone",
          isSummary: true,
        },
        affiliation: {
          type: "string",
          title: "affiliation",
          isSummary: true,
        },
      },
      required: ["name"],
    },
    section: 7,
    group: "maintenance",
    cn: "block__item--full",
  },
  {
    title: "maintenance.contractors",
    type: "array",
    items: {
      title: "contractor",
      type: "object",
      properties: {
        name: {
          type: "string",
          title: "name",
        },
        until: {
          type: "string",
          title: "until",
          widget: "date",
        },
        website: {
          type: "string",
          title: "website",
          widget: "url",
        },
      },
      required: ["name", "until"],
    },
    section: 7,
    group: "maintenance",
    cn: "block__item--full",
  },
  {
    title: "dependsOn",
    type: "array",
    items: {
      title: "dependency",
      type: "object",
      properties: {
        type: {
          title: "type",
          type: "array",
          items: {
            type: "string",
          },
          enum: ["open", "proprietary", "hardware"],
          uniqueItems: true,
          widget: "choice-expanded",
        },
        name: {
          title: "name",
          type: "string",
        },
        versionMin: {
          type: "string",
          title: "versionMin",
        },
        versionMax: {
          type: "string",
          title: "versionMax",
        },
        version: {
          type: "string",
          title: "version",
        },
        optional: {
          title: "optional",
          type: "boolean",
        },
      },
      required: ["name", "type"],
    },
    section: 7,
    cn: "block__item--full",
  },
  {
    title: "it.countryExtensionVersion",
    type: "hidden",
    section: 6,
    required: false,
    widget: "string",
    value: "0.2",
    disabled: true,
    group: "it",
  },
  {
    section: 4,
    group: "it",
    title: "it.piattaforme",
    type: "object",
    properties: {
      spid: {
        title: "spid",
        type: "boolean",
      },
      cie: {
        title: "cie",
        type: "boolean",
      },
      anpr: {
        title: "anpr",
        type: "boolean",
      },
      pagopa: {
        title: "pagopa",
        type: "boolean",
      },
    },
  },
  {
    section: 4,
    group: "it",
    title: "it.conforme",
    label: "Conforme",
    type: "object",
    properties: {
      lineeGuidaDesign: {
        title: "lineeGuidaDesign",
        type: "boolean",
      },
      modelloInteroperabilita: {
        title: "modelloInteroperabilita",
        type: "boolean",
      },
      misureMinimeSicurezza: {
        title: "misureMinimeSicurezza",
        type: "boolean",
      },
      gdpr: {
        title: "gdpr",
        type: "boolean",
      },
    },
  },
  {
    section: 3,
    prepend: true,
    group: "it",
    title: "it.riuso",
    showLabel: false,
    type: "object",
    cn: "block__item--full",
    properties: {
      codiceIPA: {
        title: "codiceIPA",
        type: "string",
        widget: "rsearch",
        ajax: {
          url:
            "https://elasticsearch.developers.italia.it/indicepa_pec/_search",
        },
      },
    },
  },
];
