const DEFAULT_VALUE_PUBLICCODE_YML = 'publiccode.yml'
const DEFAULT_VALUE_RELEASE_DATE = 'releaseDate'
const DEFAULT_VALUE_SOFTWARE_VERSION = 'softwareVersion'

export {
    DEFAULT_VALUE_PUBLICCODE_YML,
    DEFAULT_VALUE_RELEASE_DATE,
    DEFAULT_VALUE_SOFTWARE_VERSION
}
