name: Finish Release PR
permissions:
  contents: write
on:
  pull_request:
    branches: 
      - main
    types: 
      - closed

jobs:
  finish_release:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
  
      - name: Get Version
        id: v
        run: | 
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - name: Attach a tag
        run: |
          git fetch
          git checkout main
          git tag v${{ steps.v.outputs.version }}
          git push origin main
          git push --tags
      - name: Merge to Develop
        run: |
          git fetch  
          git checkout develop 
          git merge --no-ff main -m "chore: release ${{ steps.v.outputs.version }}"
          git push origin develop
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.v.outputs.version  }}
          name: Release ${{ steps.v.outputs.version  }}
          body: "Automated release for tag v${{ steps.v.outputs.version  }}"
          draft: false
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
