on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Always release the tip of the default branch
          ref: main
      - uses: italia/publiccode-softwareversion-check-action@v1.2.1
      - uses: peter-evans/create-pull-request@v7
        with:
          title: "chore: update softwareVersion and releaseDate in publiccode.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
